name: Environment
 
run-name: environment name is ${{inputs.Environment}}
 
on:
  workflow_dispatch:
    inputs:
      Environment:
        type: environment
        default: development
 
jobs:
  environment:
    runs-on: ubuntu-latest
    environment: ${{inputs.Environment}}
    steps:
      - name: name of the variable
        run: echo "name of the variable ${{vars.devvariable}}"
      - name: name of the secrets
        run: echo "name of secrets ${{secrets.devsecret}}"
      
