name: github_context workflow
run-name: github-context
on:
 push
jobs:
  github_context:
    runs-on: ubuntu-latest
    steps:
     - name: github_context
       run: |
         echo "name of the action ${{github.action}}"
         echo "name of the step ${{github.action_ref}}"
         echo "repository name of the action ${{github.action_repository}}"
         echo "username  ${{github.actor}}"
         echo "The account ID of the person ${{github.actor_id}}"
         echo "The job_id of the current job ${{github.job}}"
         echo "ref of the branch ${{github.ref}}"
         echo "unique number for each run ${{github.run_number}}"
         echo "The name of the workflow ${{github.workspace}}"
         
         

