name: matrix workflow
run-name: matrix
on:
 push
jobs:
  matrix_context:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        node-version: [v22.6.0, v21.7.3]
    steps:
     - name: node.js setup
       uses: actions/setup-node@v4.1.0
       with:
         node-version: ${{matrix.node-version}}
     - run: |
         echo " os version used ${{matrix.os}}"
         echo " node version used ${{matrix.node-version}}"
        
