name: secrets workflow
run-name: secrets
on:
 push
jobs:
  vars_context:
    runs-on: ubuntu-latest
    steps:
     - name: secrets_context
       run:
        echo " name of the password is ${{MY_PASSWORD}}"
