name: secrets workflow
run-name: secrets
on:
 push
jobs:
  vars_context:
    runs-on: ubuntu-latest
    steps:
     - name: secrets_context
       run:
        echo " encrypted password is ${{secrets.my_password}}"
